routes/web.php
<?php

if(version_compare(PHP_VERSION, '7.2.0', '>=')) {
    error_reporting(E_ALL ^ E_NOTICE ^ E_WARNING);
}
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {    
	
	if(\Auth::check()){
		if(auth()->user()->firstName == 'admin')
        	return view('adminHome');
    	else
        	return view('home');
    }
    else
    	return view('welcome');
    
});

Route::post('/contact', 'frontend\MailController@sendMail')->name('contact');

// FRONT END ROUTE ........................................

Route::group(['middleware' => 'auth'], function () 
{
	Route::get('/checkout/{token}/{token1}', 'frontend\ProductController@checkoutDetails')->name('checkout');
});

Route::group(['middleware' => ['auth'], 'prefix' => 'user', 'as' => 'user.'], function () 
{
	Route::get('/profile/{token}', 'frontend\UserController@profile')->name('profile');
	Route::get('/user-product/{token}', 'frontend\UserController@userproduct')->name('user-product');
	Route::get('/changepassword/{token}', 'frontend\UserController@changepassword')->name('changepassword');	
	Route::post('change', 'frontend\UserController@change')->name('change');
});

// FRONT END ROUTE ........................................

Route::get('/admin', function () {
    return view('admin.admin');
});


//ROUTE FOR LARAVEL FILE MANAGER ......................
Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web','auth']], function () {
     \UniSharp\LaravelFilemanager\Lfm::routes();
 });
//ROUTE FOR LARAVEL FILE MANAGER ......................

Route::middleware(['auth'])->group(function () {

	Route::get('admin/password', function () {
	    return view('admin.reset');
	});

	Route::post('/adminpassword', 'AdminController@index')->name('admin_password');
	Route::get('/admin/profile', 'AdminController@profile')->name('admin_profile');
	

	Route::get('/user', 'UserController@index')->name('user');
	Route::get('/user_add', 'UserController@show')->name('user_add');
	Route::get('/user_edit/{id}', 'UserController@edit')->name('user_edit');
	Route::put('/user_update/{id}', 'UserController@update')->name('user_update');
	Route::post('/user_add', 'UserController@store')->name('user_add');
	Route::post('/user_delete{id}', 'UserController@delete')->name('user_delete');


	// BRANCHES -----------------------------------------------------------------
	Route::get('/branches', 'BranchesController@index')->name('branches');
	Route::get('/branches_add', 'BranchesController@show')->name('branches_add');
	Route::get('/branches_edit/{id}', 'BranchesController@edit')->name('branches_edit');
	Route::put('/branches_update/{id}', 'BranchesController@update')->name('branches_update');
	Route::post('/branches_add', 'BranchesController@store')->name('branches_add');
	Route::post('/branches_delete{id}', 'BranchesController@delete')->name('branches_delete');
	// BRANCHES -----------------------------------------------------------------

	// CLIENTS -----------------------------------------------------------------
	Route::get('/clients', 'ClientsController@index')->name('clients');
	Route::get('/clients_add', 'ClientsController@show')->name('clients_add');
	Route::get('/clients_edit/{id}', 'ClientsController@edit')->name('clients_edit');
	Route::put('/clients_update/{id}', 'ClientsController@update')->name('clients_update');
	Route::post('/clients_add', 'ClientsController@store')->name('clients_add');
	Route::post('/clients_delete{id}', 'ClientsController@delete')->name('clients_delete');
	// CLIENTS -----------------------------------------------------------------

	Route::resource('page', 'PageController');

	//product CONTROLLER ROUTE BACK END
		Route::resource('product', 'productController');				
	//product CONTROLLER ROUTE BACK END
    
});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Product extends Model
{
    use SoftDeletes;
    protected $dates = ['deleted_at'];
    protected $table = 'products';
    protected $fillable = ['pName', 'pDescription', 'pPrice','pQuantity','status','deleted_at'];

}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Input;
use App\product;
use DataTables;
use DB;
use \Session, \Validator,\Redirect;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->ajax()) {

            $productQuery = product::query();

            $start_date = (!empty($_GET["start_date"])) ? ($_GET["start_date"]) : ('');
            $end_date = (!empty($_GET["end_date"])) ? ($_GET["end_date"]) : ('');

            if($start_date && $end_date){

            $start_date = date('Y-m-d', strtotime($start_date));
            $end_date = date('Y-m-d', strtotime($end_date));

            $productQuery->whereRaw("date(products.created_at ) >= '" . $start_date . "' AND date(products.created_at ) <= '" . $end_date . "'");
            }

            $data = $productQuery->select('id','pName','pDescription', 'pPrice', 'pQuantity','created_at')->orderBy('created_at','asc');

            return Datatables::of($data)
            
           ->filterColumn('pName', function($query, $keyword) {
                $query->whereRaw("pName like ?", ["%{$keyword}%"]);
            })
            ->setRowId('id')
            ->addIndexColumn()
            ->editColumn('created_at', function ($p) 
            {                
                return date('d-m-Y', strtotime($p->created_at) );
            })          
            ->addColumn('action', function ($product) {
                return '<a title="Edit" href="'.route("product.edit",base64_encode($product->id)).'" class="btn btn-xs btn-success fa fa-edit"></a>&nbsp;<a href="javascript:void(0);" title="Delete" data-delete_url="'.route("product.destroy",base64_encode($product->id)).'" data-delete_id = "'.base64_encode($product->id).'" class="btn btn-xs btn-danger delete_data fa fa-trash"></a>';
            })
            ->rawColumns(['cDescription','cThumbnail','action','cLink'])->make(true);            
            $query = $dataTable->getQuery()->get();
        }
        return view('product.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

        return view('product.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $inputs = $request->all();
        $validator = Validator::make($inputs,
        [
            'pName'         => 'required|unique:products|max:255',
            'pDescription'  => 'required',
            'pPrice'        => 'required|numeric|max:1000000000',
            'pQuantity'     => 'required|numeric|max:1000000000',
            //'cFile'         => 'sometimes|mimes:jpeg,jpg,png,gif,pdf,docx,doc,xls,xlsx|max:100000'
        ]);

        if($validator->fails()){
            $message = $validator->messages();        
            return Redirect::back()->withErrors($validator)->withInput();
        }
        else{

            $check_Venue_start_data = product::where('pName',$inputs['pName'])->first();

            if(count($check_Venue_start_data) == 0){

                /*if($request->cThumbnail != ''){
                    $cThumbnail = time().".".$request->cThumbnail->getClientOriginalExtension();
                    \Image::make($request->cThumbnail)->save(public_path('img/product/').$cThumbnail);  
                }
                else
                    $cThumbnail = '';*/
              
                /*if (request()->hasFile('cFile')){
                    $image = Input::file('cFile');
                    $uploadedImage = $request->file('cFile');
                    $cFile = time() . '.' . $image->getClientOriginalExtension();
                    $destinationPath = public_path('/img/product/');
                    $uploadedImage->move($destinationPath, $cFile);
                    $image->imagePath = $destinationPath . $cFile;
                }            
                else
                    $cFile = '';*/

                $product = new product([
                    'pName'           => $inputs['pName'],
                    'pDescription'    => $inputs['pDescription'],
                    'pPrice'           => $inputs['pPrice'],
                    'pQuantity'      => $inputs['pQuantity'],
                    'created_at'      => date('Y-m-d H:i:s')
                ]);
                $product->save();
                return redirect('/product')->with('success', 'Product Added Successfully');
            }
            else
                return redirect('/product')->with('error', 'Another product exist.');
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $productId=base64_decode($id);
        $product = product::find($productId);
        return view('product.edit', compact('product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $productId = base64_decode($id);
        $inputs = $request->all();
        $validator = Validator::make($inputs,
        [
            'pName'         => 'required|unique:products,pName,"'.$productId.'"',
            'pDescription'  => 'required',
            'pPrice'        => 'required|numeric|max:1000000000',
            'pQuantity'     => 'required|numeric|max:1000000000'
            //'cFile'         => 'sometimes|mimes:jpeg,jpg,png,gif,pdf,docx,doc,xls,xlsx|max:100000'
        ]);

        if($validator->fails()){
            $message = $validator->messages();        
            return Redirect::back()->withErrors($validator)->withInput();
        }
        else{

            $check_Venue_start_data = product::where('id','!=',$productId)->where('pName',$inputs['pName'])->first();

            if(count($check_Venue_start_data) == 0){
                $product = product::findOrFail($productId);

                /*if($request->cThumbnail != ''){
                    $cThumbnail = time().".".$request->cThumbnail->getClientOriginalExtension();
                    \Image::make($request->cThumbnail)->save(public_path('img/product/').$cThumbnail);  
                }
                else{
                    if($product->cThumbnail == '')
                        $cThumbnail = '';
                    else
                        $cThumbnail = $product->cThumbnail;
                }*/
              
                /*if (request()->hasFile('cFile')){
                    $image = Input::file('cFile');
                    $uploadedImage = $request->file('cFile');
                    $cFile = time() . '.' . $image->getClientOriginalExtension();
                    $destinationPath = public_path('/img/product/');
                    $uploadedImage->move($destinationPath, $cFile);
                    $image->imagePath = $destinationPath . $cFile;
                }            
                else{
                    if($product->cFile == '')
                        $cFile = '';
                    else
                        $cFile = $product->cFile;
                }*/

                $product->pName         = $inputs['pName'];
                $product->pDescription  = $inputs['pDescription'];
                $product->pPrice        = $inputs['pPrice'];
                $product->pQuantity     = $inputs['pQuantity'];                
                //$product->cFile         = $cFile;                
                $product->updated_at    = date('Y-m-d H:i:s');

                $product->save();    
                return redirect('/product')->with('success', 'product Data Updated Successfully');
            }
            else
                return redirect('/product')->with('error', 'Another product exist.');
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */   

    public function destroy($id)
    {
        $id = base64_decode($id);
        $product = product::find( $id );
        $product->delete();
        //Session::put('success', 'product Deleted Successfully');
        return response()->json(['status'=>1,'dataId'=>$id]);        
    }    
}

resources/views/product/add.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
<h1>Add product</h1>
@stop
@section('content')

{!! Form::open(array('route'=>'product.store','class'=>'form-horizontal','method'=>'post', 'role'=>'form', 'files'=> true)) !!}
<div>   
    <div class="box-body mt-4">
        <div class="main">
            <div class="main-inner">
                <div class="container">
                    <div class="widget-content">
                        <fieldset>
                            <div class="row">

                                <div class="col-xs-10 col-sm-7">
                                    <div
                                        class="control-group required{{ $errors->has('pName') ? ' has-error' : '' }}">
                                        <label class="control-label" for="pName">Name</label>
                                        <div class="controls">
                                            <input type="text" maxlength="100" class="form-control"
                                                placeholder="product Name" name="pName" class="span3" id="pName"
                                                value="{{ old('pName') }}" required autofocus />
                                            @if ($errors->has('pName')) <span class="help-block">
                                                <strong>{{ $errors->first('pName') }}</strong> </span> @endif </div>
                                    </div>
                                </div>


                                <div class="col-xs-10 col-sm-7">
                                    <div
                                        class="control-group required{{ $errors->has('pDescription') ? ' has-error' : '' }}">
                                        <label class="control-label" for="pDescription">Description</label>
                                        <div class="controls">
                                            <textarea class="form-control my-editor" name="pDescription"  id="pDescription" rows="5" value="{{ old('pDescription') }}" required autofocus>
                                                </textarea>
                                            @if ($errors->has('pDescription')) <span class="help-block">
                                                <strong>{{ $errors->first('pDescription') }}</strong> </span> @endif </div>
                                    </div>
                                </div>

                                <div class="col-xs-10 col-sm-7">
                                    <div class="control-group required{{ $errors->has('pPrice') ? ' has-error' : '' }}">
                                        <label class="control-label" for="pPrice">Price</label>
                                        <div class="controls">
                                            <input type="text" class="form-control" placeholder="product Venue"
                                                name="pPrice" class="span3" id="pPrice" value="{{ old('pPrice') }}"
                                                required autofocus />
                                            @if ($errors->has('pPrice')) <span class="help-block">
                                                <strong>{{ $errors->first('pPrice') }}</strong> </span> @endif </div>
                                    </div>
                                </div>

                                <div class="col-xs-10 col-sm-7">
                                    <div class="control-group required{{ $errors->has('pQuantity') ? ' has-error' : '' }}">
                                        <label class="control-label" for="pQuantity">Quantity</label>
                                        <div class="controls">
                                            <input type="text" class="form-control" placeholder="product Venue"
                                                name="pQuantity" class="span3" id="pQuantity" value="{{ old('pQuantity') }}"
                                                required autofocus />
                                            @if ($errors->has('pQuantity')) <span class="help-block">
                                                <strong>{{ $errors->first('pQuantity') }}</strong> </span> @endif </div>
                                    </div>
                                </div>


                                <!-- <div class="col-xs-10 col-sm-7">
                                    <div class="control-group{{ $errors->has('cThumbnail') ? ' has-error' : '' }}">
                                        <label class="control-label" for="cThumbnail">Thumbnail</label>
                                        <div class="controls">
                                            <input type="file" class="form-control"
                                                placeholder="product Price" name="cThumbnail" id="cThumbnail"
                                                autofocus />
                                            @if ($errors->has('cThumbnail')) <span class="help-block">
                                                <strong>{{ $errors->first('cThumbnail') }}</strong> </span> @endif </div>
                                    </div>
                                </div>

                                <div class="col-xs-10 col-sm-7">
                                    <div
                                        class="control-group required{{ $errors->has('cFile') ? ' has-error' : '' }}">
                                        <label class="control-label" for="cFile">File</label>
                                        <div class="controls">
                                            <input class="date form-control"  type="file" name="cFile" id="cFile">
                                            @if ($errors->has('cFile')) <span class="help-block">
                                                <strong>{{ $errors->first('cFile') }}</strong> </span> @endif
                                        </div>
                                    </div>
                                </div> -->

                               <div class="col-xs-10 col-sm-7" style="margin-top:45px;">
                                    <div class="form-actions">
                                    <input type="submit" class="btn btn-primary" value="Save" />
                                    <a onclick="window.history.go(-1); return false;" class="btn btn-danger">Cancel</a> </div>
                                </div>
                            </div>
                        </fieldset>
                    </div>
                </div>
            </div>
      </div>
  </div>
{!! Form::close() !!}
@stop

resources/views/product/edit.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
<h1>Edit Product</h1>
@stop
@section('content')

    {!!
    Form::open(array('route'=>array('product.update',base64_encode($product->id)),'class'=>'form-horizontal','method'=>'put',
    'role'=>'form','files'=>true)) !!}    
    <div>   
        <div class="box-body mt-4">
        <div class="main">
            <div class="main-inner">
                <div class="container">
                    <div class="widget-content">
                        <fieldset>
                            <div class="row">

                                <div class="col-xs-10 col-sm-7">
                                    <div
                                        class="control-group required{{ $errors->has('pName') ? ' has-error' : '' }}">
                                        <label class="control-label" for="pName">Name</label>
                                        <div class="controls">
                                            <input type="text" maxlength="100" class="form-control"
                                                placeholder="product Name" name="pName" class="span3" id="pName"
                                                value="{{ $product->pName }}" required autofocus />
                                            @if ($errors->has('pName')) <span class="help-block">
                                                <strong>{{ $errors->first('pName') }}</strong> </span> @endif </div>
                                    </div>
                                </div>


                                <div class="col-xs-10 col-sm-7">
                                    <div
                                        class="control-group required{{ $errors->has('pDescription') ? ' has-error' : '' }}">
                                        <label class="control-label" for="pDescription">Description</label>
                                        <div class="controls">
                                            <textarea class="form-control my-editor" name="pDescription"  id="pDescription" rows="5" required autofocus>{{ $product->pDescription }}
                                                </textarea>
                                            @if ($errors->has('pDescription')) <span class="help-block">
                                                <strong>{{ $errors->first('pDescription') }}</strong> </span> @endif </div>
                                    </div>
                                </div>

                                <div class="col-xs-10 col-sm-7">
                                    <div class="control-group required{{ $errors->has('pPrice') ? ' has-error' : '' }}">
                                        <label class="control-label" for="pPrice">Price</label>
                                        <div class="controls">
                                            <input type="text" class="form-control" placeholder="product Venue"
                                                name="pPrice" class="span3" id="pPrice" value="{{ $product->pPrice }}"
                                                required autofocus />
                                            @if ($errors->has('pPrice')) <span class="help-block">
                                                <strong>{{ $errors->first('pPrice') }}</strong> </span> @endif </div>
                                    </div>
                                </div>


                                <div class="col-xs-10 col-sm-7">
                                    <div class="control-group required{{ $errors->has('pQuantity') ? ' has-error' : '' }}">
                                        <label class="control-label" for="pQuantity">Quantity</label>
                                        <div class="controls">
                                            <input type="text" class="form-control" placeholder="product Venue"
                                                name="pQuantity" class="span3" id="pQuantity" value="{{ $product->pQuantity }}"
                                                required autofocus />
                                            @if ($errors->has('pQuantity')) <span class="help-block">
                                                <strong>{{ $errors->first('pQuantity') }}</strong> </span> @endif </div>
                                    </div>
                                </div>

                               <div class="col-xs-10 col-sm-7" style="margin-top:45px;">
                                    <div class="form-actions">
                                    <input type="submit" class="btn btn-primary" value="Update" />
                                    <a onclick="window.history.go(-1); return false;" class="btn btn-danger">Cancel</a> </div>
                                </div>
                            </div>
                        </fieldset>
                    </div>
                </div>
            </div>
      </div>
    </div>
    {!! Form::close() !!}
    

@stop

resources/views/product/index.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')

@stop
@section('content')

<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">Product List</h3>
    </div>
    <div class="row">
        <div class="form-group col-md-4">
            <h5>Start Date <span class="text-danger"></span></h5>
            <div class="controls">
                <input type="date" name="start_date" id="start_date" class="form-control datepicker-autoclose" placeholder="Please select start date"> 
                <div class="help-block"></div>
            </div>
        </div>
        <div class="form-group col-md-4">
            <h5>End Date <span class="text-danger"></span></h5>
            <div class="controls">
                <input type="date" name="end_date" id="end_date" class="form-control datepicker-autoclose" placeholder="Please select end date"> <div class="help-block"></div>
            </div>
        </div>
        <div class="form-group col-md-4 text-left" style="margin-top: 35px;">
            <button type="text" id="btnFiterSubmitSearch" class="btn btn-info">Submit</button>
        </div>
    </div>
    <div class="row">

        <div class="col-md-12"><a href="{{URL::route('product.create')}}" class="btn btn-info pull-right createbtn"
                style="margin:15px;">Add New</a></div>
    </div>

    <table class="table" id="example">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Name</th>
                <th scope="col">Description</th>
                <th scope="col">Price per unit</th>
                <th scope="col">Quantity</th>
                <th scope="col">Created At</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>

        </tbody>
    </table>
</div>
@stop
@section('js')
<script>
$(function() {
    var table = $('#example').DataTable({
        processing: true,
        serverSide: true,
        ajax: {
            'url': '{{ route("product.index") }}',
            'type': 'GET',            
            data: function (d) {
              d.start_date = $('#start_date').val();
              d.end_date = $('#end_date').val();
            },
            'headers': {
                'X-CSRF-TOKEN': '{{ csrf_token() }}'
            }
        },
        columns: [{
                data: 'DT_RowIndex',
                name: 'DT_RowIndex',
                orderable: false,
                searchable: false
            },
            {   data: 'pName',name: 'pName' },
            {   data: 'pDescription',name: 'pDescription' },
            {   data: 'pPrice',name: 'pPrice' },
            {   data: 'pQuantity',name: 'pQuantity' },
            {   data: 'created_at',name: 'created_at' },
            {   data: 'action',name: 'action', orderable: false,searchable: false },
        ]
    });

    $('#btnFiterSubmitSearch').click(function(){
        $('#example').DataTable().draw(true);
    });

    $(document).on('click', '.delete_data', function() {
        $('#delete_modal').modal('show');

        var url = $(this).data('delete_url');
        var delete_id = $(this).data('delete_id');
        $('#submit').attr('data-target_url', url);
        $('#submit').attr('data-delete_id', delete_id);
    });

    $(document).on('click', '#submit', function() {
        var url = $(this).attr('data-target_url');
        var rowid = $(this).attr('data-delete_id');
        $('#delete_modal').modal('hide');
        $.ajax({
            type: 'delete',
            url: url,
            dataType: 'json',
            headers: {
                'X-CSRF-TOKEN': '{{ csrf_token() }}'
            },
            success: function(data) {
                var row = document.getElementById(data.dataId);
                row.parentElement.removeChild(row);
                //window.location.reload();
            }
        });
    });    
});
</script>
<div class="modal" id="delete_modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Information</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this record?</p>
            </div>
            <div class="modal-footer">
                <a href="javascript:void(0);" id="submit" data-delete_id="" data-target_url="" class="btn btn-danger">Yes</a>
                <button class="btn btn-primary" data-dismiss="modal" aria-hidden="true">No</button>
            </div>
        </div>
    </div>
</div>
@stop