routes/web.php
<?php

if(version_compare(PHP_VERSION, '7.2.0', '>=')) {
    error_reporting(E_ALL ^ E_NOTICE ^ E_WARNING);
}
/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {    
	
	if(\Auth::check()){
		if(auth()->user()->firstName == 'admin')
        	return view('adminHome');
    	else
        	return view('home');
    }
    else
    	return view('welcome');
    
});

Route::post('/contact', 'frontend\MailController@sendMail')->name('contact');

// FRONT END ROUTE ........................................

Route::group(['middleware' => 'auth'], function () 
{
	Route::get('/checkout/{token}/{token1}', 'frontend\ProductController@checkoutDetails')->name('checkout');
});

Route::group(['middleware' => ['auth'], 'prefix' => 'user', 'as' => 'user.'], function () 
{
	Route::get('/profile/{token}', 'frontend\UserController@profile')->name('profile');
	Route::get('/user-product/{token}', 'frontend\UserController@userproduct')->name('user-product');
	Route::get('/changepassword/{token}', 'frontend\UserController@changepassword')->name('changepassword');	
	Route::post('change', 'frontend\UserController@change')->name('change');
});

// FRONT END ROUTE ........................................

Route::get('/admin', function () {
    return view('admin.admin');
});


//ROUTE FOR LARAVEL FILE MANAGER ......................
Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web','auth']], function () {
     \UniSharp\LaravelFilemanager\Lfm::routes();
 });
//ROUTE FOR LARAVEL FILE MANAGER ......................

Route::middleware(['auth'])->group(function () {

	Route::get('admin/password', function () {
	    return view('admin.reset');
	});

	Route::post('/adminpassword', 'AdminController@index')->name('admin_password');
	Route::get('/admin/profile', 'AdminController@profile')->name('admin_profile');
	

	Route::get('/user', 'UserController@index')->name('user');
	Route::get('/user_add', 'UserController@show')->name('user_add');
	Route::get('/user_edit/{id}', 'UserController@edit')->name('user_edit');
	Route::put('/user_update/{id}', 'UserController@update')->name('user_update');
	Route::post('/user_add', 'UserController@store')->name('user_add');
	Route::post('/user_delete{id}', 'UserController@delete')->name('user_delete');


	// BRANCHES -----------------------------------------------------------------
	Route::get('/branches', 'BranchesController@index')->name('branches');
	Route::get('/branches_add', 'BranchesController@show')->name('branches_add');
	Route::get('/branches_edit/{id}', 'BranchesController@edit')->name('branches_edit');
	Route::put('/branches_update/{id}', 'BranchesController@update')->name('branches_update');
	Route::post('/branches_add', 'BranchesController@store')->name('branches_add');
	Route::post('/branches_delete{id}', 'BranchesController@delete')->name('branches_delete');
	// BRANCHES -----------------------------------------------------------------

	// CLIENTS -----------------------------------------------------------------
	Route::get('/clients', 'ClientsController@index')->name('clients');
	Route::get('/clients_add', 'ClientsController@show')->name('clients_add');
	Route::get('/clients_edit/{id}', 'ClientsController@edit')->name('clients_edit');
	Route::put('/clients_update/{id}', 'ClientsController@update')->name('clients_update');
	Route::post('/clients_add', 'ClientsController@store')->name('clients_add');
	Route::post('/clients_delete{id}', 'ClientsController@delete')->name('clients_delete');
	// CLIENTS -----------------------------------------------------------------

	Route::resource('page', 'PageController');

	//product CONTROLLER ROUTE BACK END
		Route::resource('product', 'productController');				
	//product CONTROLLER ROUTE BACK END
    
});

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

resources/views/page/add.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
<h1>Add page</h1>
@stop
@section('content')

{!! Form::open(array('route'=>'page.store','class'=>'form-horizontal','method'=>'post', 'role'=>'form', 'files' => true)) !!}
<div>   
    <div class="box-body mt-4">
        <div class="main">
            <div class="main-inner">
                <div class="container">
                    <div class="widget-content">
                        <fieldset>
                            <div class="row">

                                <div class="col-xs-10 col-sm-7">
                                    <div
                                        class="control-group required{{ $errors->has('title') ? ' has-error' : '' }}">
                                        <label class="control-label" for="title">Name</label>
                                        <div class="controls">
                                            <input type="text" maxlength="100" class="form-control"
                                                placeholder="page Name" name="title" class="span3" id="title"
                                                value="{{ old('title') }}" required autofocus />
                                            @if ($errors->has('title')) <span class="help-block">
                                                <strong>{{ $errors->first('title') }}</strong> </span> @endif </div>
                                    </div>
                                </div>


                                <div class="col-xs-10 col-sm-7">
                                    <div
                                        class="control-group required{{ $errors->has('content') ? ' has-error' : '' }}">
                                        <label class="control-label" for="content">Description</label>
                                        <div class="controls">
                                            <textarea class="form-control my-editor" name="content"  id="my-editor" rows="5" value="{{ old('content') }}" required autofocus>
                                                </textarea>
                                            @if ($errors->has('content')) <span class="help-block">
                                                <strong>{{ $errors->first('content') }}</strong> </span> @endif </div>
                                    </div>
                                </div>

                                <div class="col-xs-10 col-sm-7">
                                    <div class="control-group required{{ $errors->has('image') ? ' has-error' : '' }}">
                                        <label class="control-label" for="image">File</label>
                                        <div class="controls">
                                            <input type="file" maxlength="100" class="form-control" placeholder="page Venue"
                                                name="image" class="span3" id="image" value="{{ old('image') }}"
                                                autofocus />
                                            @if ($errors->has('image')) <span class="help-block">
                                                <strong>{{ $errors->first('image') }}</strong> </span> @endif </div>
                                    </div>
                                </div>

                               <div class="col-xs-10 col-sm-7" style="margin-top:45px;">
                                    <div class="form-actions">
                                    <input type="submit" class="btn btn-primary" value="Save" />
                                    <a onclick="window.history.go(-1); return false;" class="btn btn-danger">Cancel</a> </div>
                                </div>
                            </div>
                        </fieldset>
                    </div>
                </div>
            </div>
      </div>
  </div>
{!! Form::close() !!}
@stop

resources/views/page/edit.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')
<h1>Edit page</h1>
@stop
@section('content')

    {!!
    Form::open(array('route'=>array('page.update',base64_encode($page->id)),'class'=>'form-horizontal','method'=>'put',
    'role'=>'form', 'files' => true)) !!}    
    <div>   
        <div class="box-body mt-4">
        <div class="main">
            <div class="main-inner">
                <div class="container">
                    <div class="widget-content">
                        <fieldset>
                            <div class="row">

                                <div class="col-xs-10 col-sm-7">
                                    <div
                                        class="control-group required{{ $errors->has('title') ? ' has-error' : '' }}">
                                        <label class="control-label" for="title">Name</label>
                                        <div class="controls">
                                            <input type="text" maxlength="100" class="form-control"
                                                placeholder="page Name" name="title" class="span3" id="title"
                                                value="{{ $page->title }}" required autofocus />
                                            @if ($errors->has('title')) <span class="help-block">
                                                <strong>{{ $errors->first('title') }}</strong> </span> @endif </div>
                                    </div>
                                </div>


                                <div class="col-xs-10 col-sm-7">
                                    <div
                                        class="control-group required{{ $errors->has('content') ? ' has-error' : '' }}">
                                        <label class="control-label" for="content">Description</label>
                                        <div class="controls">
                                            <textarea class="form-control my-editor" name="content"  id="my-editor" rows="5" value="{{ old('content') }}" required autofocus>{{ $page->content }}
                                                </textarea>
                                            @if ($errors->has('content')) <span class="help-block">
                                                <strong>{{ $errors->first('content') }}</strong> </span> @endif </div>
                                    </div>
                                </div>

                                <div class="col-xs-10 col-sm-7">
                                    <div class="control-group required{{ $errors->has('image') ? ' has-error' : '' }}">
                                        <label class="control-label" for="image">File</label>
                                        <div class="controls">
                                            <input type="file" maxlength="100" class="form-control" placeholder="page Venue"
                                                name="image" class="span3" id="image" value="{{ old('image') }}"
                                                autofocus />
                                            @if ($errors->has('image')) <span class="help-block">
                                                <strong>{{ $errors->first('image') }}</strong> </span> @endif </div>
                                    </div>
                                </div>                   

                               <div class="col-xs-10 col-sm-7" style="margin-top:45px;">
                                    <div class="form-actions">
                                    <input type="submit" class="btn btn-primary" value="Update" />
                                    <a onclick="window.history.go(-1); return false;" class="btn btn-danger">Cancel</a> </div>
                                </div>
                            </div>
                        </fieldset>
                    </div>
                </div>
            </div>
      </div>
    </div>
    {!! Form::close() !!}
    

@stop

resources/views/page/index.blade.php
@extends('adminlte::page')

@section('title', 'AdminLTE')

@section('content_header')

@stop
@section('content')

<div class="box">
    <div class="box-header with-border">
        <h3 class="box-title">Page List</h3>
    </div>

    <div class="row">
        <div class="col-md-12"><a href="{{URL::route('page.create')}}" class="btn btn-info pull-right createbtn"
                style="margin:15px;">Add New</a></div>
    </div>

    <table class="table" id="example">
        <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Title</th>
                <th scope="col">Description</th>
                <th scope="col">Image</th>
                <th scope="col">Created At</th>
                <th scope="col">Action</th>
            </tr>
        </thead>
        <tbody>

        </tbody>
    </table>
</div>
@stop
@section('js')
<script>
$(function() {
    var table = $('#example').DataTable({
        processing: true,
        serverSide: true,
        ajax: {
            'url': '{{ route("page.index") }}',
            'type': 'GET',
            'headers': {
                'X-CSRF-TOKEN': '{{ csrf_token() }}'
            }
        },
        columns: [{
                data: 'DT_RowIndex',
                name: 'DT_RowIndex',
                orderable: false,
                searchable: false
            },
            {
                data: 'title',
                name: 'title'
            },
            {
                data: 'content',
                name: 'content'
            },
            {
                data: 'image',
                name: 'image'
            },
            {
                data: 'created_at',
                name: 'created_at'
            },            
            {
                data: 'action',
                name: 'action',
                orderable: false,
                searchable: false
            },
        ]
    });

    $(document).on('click', '.delete_data', function() {
        $('#delete_modal').modal('show');

        var url = $(this).data('delete_url');
        var delete_id = $(this).data('delete_id');
        $('#submit').attr('data-target_url', url);
        $('#submit').attr('data-delete_id', delete_id);
    });

    $(document).on('click', '#submit', function() {
        var url = $(this).attr('data-target_url');
        var rowid = $(this).attr('data-delete_id');
        $('#delete_modal').modal('hide');
        $.ajax({
            type: 'delete',
            url: url,
            dataType: 'json',
            headers: {
                'X-CSRF-TOKEN': '{{ csrf_token() }}'
            },
            success: function(data) {
                var row = document.getElementById(data.dataId);
                row.parentElement.removeChild(row);
                //window.location.reload();
            }
        });
    });    
});
</script>
<div class="modal" id="delete_modal" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Information</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete this record?</p>
            </div>
            <div class="modal-footer">
                <a href="javascript:void(0);" id="submit" data-delete_id="" data-target_url="" class="btn btn-danger">Yes</a>
                <button class="btn btn-primary" data-dismiss="modal" aria-hidden="true">No</button>
            </div>
        </div>
    </div>
</div>
@stop